apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: imagestoretoexternal
spec:
  rewrite-policies:
    - servicenames:
        - bookroom-frontend
      rewrite-policy:
        operation: replace_all
        target: 'HTTP.RES.BODY(HTTP.RES.CONTENT_LENGTH)'
        modify-expression: '"http://external.images.bookroom.com"'
        multiple-occurence-modify: 'text("http://images.bookroom.com")'
        comment: 'Replace Internal URL to External URL'
        direction: RESPONSE
        rewrite-criteria: 'HTTP.RES.IS_VALID'
